# Banco de frases para @carolina.cuevas.libros
# Todas salen de «No estás rota, estás cansada» (Carolina Cuevas), literales o reformuladas.
# Formato: (texto, leyenda, corazón)
#   texto: "\n" = salto de línea, *...* = subrayado a mano
#   leyenda: texto del pie de foto (sin la parte de llamada a la acción, que se añade sola)

FRASES = [
    # 1
    ("No vas tarde.\nNo estás rota.\n*Estás cansada,*\nque es otra cosa\ncompletamente distinta.\nY de eso *sí se sale.*",
     "Para la que lleva años haciéndolo todo bien y aun así siente que no alcanza. 🤍", True),
    ("Esa voz que te dice\nque no eres suficiente\nno nació contigo.\n*La aprendiste.*\nY lo aprendido\ntambién se puede soltar.",
     "Nadie elige la voz que le habla por dentro. Pero sí puedes dejar de obedecerla. 🌿", True),
    ("Hoy hiciste muchas cosas.\nPero a las once de la noche\nsolo aparece\n*la lista de lo que falta.*",
     "Las dos listas son ciertas. Solo una te deja dormir. 🌙", True),
    ("Descansar\nno debería necesitar permiso.\n*Tampoco factura.*",
     "Si tienes que ganarte el descanso, alguien te enseñó a vivir en deuda. 🤍", True),
    ("La mujer que llevas años\nintentando ser\nsiempre está\n*a la misma distancia.*",
     "Cada vez que avanzas, ella avanza también. Ese es su diseño. 🌿", True),
    ("No es falta de disciplina.\nEs que llevas años\ntrabajando para alguien\nque nunca está contento contigo.\n*Aunque ese alguien seas tú.*",
     "Léelo otra vez, despacio. 🤍", False),
    ("Es un cansancio\n*de las que se implican,*\nno de las que se rinden.",
     "Si te sientes así, no es porque hiciste poco. Es porque llevas años dándolo todo. ✨", True),
    ("Una meta puede darte\nun resultado.\nNo puede darte\n*permiso para estar en paz.*",
     "Ese permiso no lo firma ningún logro. Lo firmas tú. 🤍", True),
    ("Si se lo dijeras a una amiga,\nte parecería cruel.\n*¿Por qué contigo\nsí vale?*",
     "Háblate como le hablarías a alguien que quieres. 💛", True),
    ("No eres tus pensamientos.\n*Eres la que los está\nescuchando.*",
     "Un pensamiento repetido mil veces no se vuelve verdad. Solo se vuelve costumbre. 🌿", True),
    # 11
    ("Lo que consigues\ndeja de contar\nen cuanto lo consigues.\n*Por eso nunca sientes\nque avanzas.*",
     "No es humildad. Es un error de contabilidad. ✨", True),
    ("Cuando termine esto,\npor fin voy a estar tranquila.\n\n*Y llega el día.\nY aparece otro «cuando».*",
     "La calma no es un premio. Es un lugar desde donde se vive. 🤍", False),
    ("El miedo funciona.\nTe levanta temprano,\ncumple plazos, no falla.\n*Lo que pasa es que cobra.*",
     "Y cobra en cansancio que no se quita durmiendo. 🌿", False),
    ("No hace falta\nque te perdones nada.\nHiciste lo que sabías\ncon lo que tenías.\n*Ahora sabes otra cosa.*",
     "Eso es todo lo que ha cambiado. Y es suficiente. 🤍", True),
    ("Un límite\n*no necesita justificación*\npara ser válido.",
     "No puedo el sábado. Punto. Sin expediente. ✨", True),
    ("Déjame que lo mire\ny te digo.",
     "Cinco palabras que te devuelven el tiempo para decidir desde ti. 💛", True),
    ("Que algo vuelva a doler\nno significa\nque no hayas avanzado.\n*Significa que era importante.*",
     "Lo importante no se cierra del todo. Se va haciendo pequeño. 🤍", True),
    ("No volviste\nal punto de partida.\n*Estás en una espiral.*\nPasa por el mismo lado,\npero cada vez más arriba.",
     "Para el día en que creas que retrocediste. 🌿", True),
    ("Tú no eres un proyecto.\nEres una persona.\n*Y una persona\nnunca está a medias.*",
     "No hay versión final de ti. Solo una mujer, un martes, haciendo lo que puede. 🤍", True),
    ("Nunca estuviste rota.\n*Sigue creciendo.*\nSolo que ya no desde ahí.",
     "Lo que cambia no es lo que haces. Es desde dónde lo haces. ✨", True),
    # 21
    ("¿Desde dónde\nestás creciendo?\n*¿Desde el miedo\no desde la calma?*",
     "Es la única pregunta que necesitas hacerte mañana. 🌿", True),
    ("Te dijeron\n«tú puedes más».\n*Que es lo mismo que\n«todavía no alcanzas»,\npero entra sin hacer ruido.*",
     "No fuiste ingenua. Hiciste lo que se esperaba de ti. 🤍", False),
    ("La lista de cosas\nque mejorar de ti\n*no está hecha\npara terminarse.*",
     "Tachas una y aparece otra. No es tu culpa: es su diseño. ✨", True),
    ("Mismas rutinas.\nMismos libros.\nMismo esfuerzo.\n*Motivo opuesto.*",
     "Una construye. La otra solo intenta no perder. 🌿", True),
    ("Lo que harías\nsi ya estuvieras bien\n*podrías hacerlo\nel jueves.*",
     "No es el premio por estar bien. Es, en parte, lo que te pone bien. 💛", True),
    ("La calma\nno llega cuando terminas algo.\n*Se tiene o no se tiene\nmientras lo haces.*",
     "Y el alivio, por naturaleza, dura poco. 🤍", True),
    ("Ser exigente\nno es lo mismo\nque *despreciarte.*",
     "Una entrenadora buena te exige mucho y te habla bien. Las dos cosas a la vez. ✨", True),
    ("«No puedes hacer nada bien.»\n\nSe te quemó la cena.\n*Nada más.*",
     "Del hecho al veredicto, sin escalas. Vuelve al hecho. 🌿", True),
    ("Lo que se queda años\nno es lo que sentiste.\n*Es lo que no te dejaste\nsentir.*",
     "Una emoción que no se combate dura mucho menos de lo que temes. 🤍", False),
    ("Soltar\nno es olvidar.\nNo es perdonar.\n*Es dejar de pelear\ncon lo que ya pasó.*",
     "Levantarte de una mesa donde no había nada que negociar. 🌿", True),
    # 31
    ("Dieciocho días bien\ny una noche mala\n*no son cero días.*",
     "Cuenta en días, no en rachas. Mañana sigues. 💛", True),
    ("Rompí hoy.\n*Mañana sigo.*\nSin discurso.\nSin ceremonia.",
     "Para la próxima vez que falles en algo que te habías propuesto. 🤍", True),
    ("Que otras estén peor\n*no convierte tu cansancio\nen un capricho.*",
     "Puedes tener cosas buenas y estar agotada. Las dos a la vez. 🌿", True),
    ("Mira quién aparece\ncuando estás mal\n*y quién desaparece\ncuando estás bien.*",
     "No todos saben quererte de pie. 🤍", False),
    ("Con esta persona,\n¿me siento\n*más grande\no más pequeña?*",
     "No después de una discusión. En el promedio de los meses. ✨", True),
    ("No esperes a estar tranquila\npara hablar.\n*Nota desde dónde hablas\nmientras hablas.*",
     "El miedo no desaparece. Solo deja de conducir. 🌿", True),
    ("La memoria\nno guarda mejoras.\n*Solo guarda pendientes.*",
     "Por eso hay que escribir lo que ya cambió. ✨", True),
    ("Ya no te disculpas por todo.\nYa no le das tres días\na un comentario.\n*Eso también es avanzar.*",
     "Los cambios de fondo no tienen diploma. Pero son reales. 🤍", True),
    ("Un niño de tres años\nno se pregunta\nsi es suficiente.\n*Esa duda se aprende después.*",
     "Y lo que se aprende se puede desaprender. 🌿", True),
    ("Dile a tu yo de hace cinco años\nlo que resolviste desde entonces.\n*No lo creería.*",
     "Escribe cinco cosas que hoy ya no son un problema. 💛", True),
    # 41
    ("Un juez\nque nunca absuelve\n*no es un juez.*",
     "Esa voz de las once de la noche nunca te ha felicitado. Fíjate. 🌙", False),
    ("Llevas años preparándote\npara vivir.\n*Es la sala de espera\nmás larga del mundo.*",
     "Y tiene una particularidad: nunca llaman tu número. 🤍", True),
    ("Lo más pequeño\nque harías si te sintieras\nsuficiente.\n*Eso. Esta semana.*",
     "No una lista más. Una sola cosa, tan pequeña que dé risa. ✨", True),
    ("Firmeza:\n«esto hay que hacerlo».\nDureza:\n*«y si no, ya sabemos\nlo que eres».*",
     "Quítale la segunda parte a la frase. La primera funciona igual. 🌿", True),
    ("Si tu frase\nno termina en algo\nque puedas hacer mañana,\n*no era corrección.\nEra castigo.*",
     "«No fui a caminar, así que mañana voy a las siete.» Eso sí. 💛", True),
    ("No es que hagas\ndemasiado poco.\n*Es que nada\nte parece suficiente.*",
     "Y eso no se resuelve haciendo más. 🤍", False),
    ("Ninguna de las dos\nlo hace mejor.\nUna camina porque le gusta.\n*La otra, para no sentirse\nculpable.*",
     "Lo que no se ve desde afuera es lo que lo decide todo. 🌿", True),
    ("La culpa al descansar\naparece cuando crees\n*que vas atrasada.*",
     "No vas atrasada. Nunca hubo una fecha. ✨", True),
    ("Por eso el cansancio\nno se va con vacaciones.\n*La sensación de deuda\nse sube contigo al avión.*",
     "Lo que cansa no era el trabajo. 🤍", False),
    ("Leer para entender\nno es lo mismo que\n*leer para que\npor fin te salven.*",
     "Sigue leyendo. Solo fíjate en qué sientes cuando terminas un libro. 📖", True),
    # 51
    ("Esa voz que te corrige\ntiene acento.\n*¿De quién es?*",
     "Nadie inventa un estilo así de la nada. 🌿", True),
    ("Durante años creíste\nque escuchabas\nla verdad sobre ti.\n*Escuchabas una herencia.*",
     "Y una herencia se puede revisar sin odiar a nadie. 🤍", False),
    ("Las cadenas\nse pueden cortar\n*sin odiar a nadie.*",
     "No estás enfrentándote a nadie. Estás siendo la primera que se para a mirar. ✨", True),
    ("Esa parte de ti\nque tanto criticas\n*te protegió\nen su momento.*",
     "No hay que pelear con ella. Hay que avisarle de que su turno terminó. 🌿", True),
    ("Llevas el abrigo de invierno\nen agosto\n*porque en enero\nte salvó del frío.*",
     "Las voces que te protegieron no saben que ya creciste. 🤍", True),
    ("Lo que combates\n*se defiende.*",
     "Por eso la guerra contigo misma siempre te deja más cansada. 🌿", True),
    ("No se trata de pensar\ncosas bonitas.\n*Se trata de dejar de\nobedecer a las feas.*",
     "Los pensamientos difíciles no se van. Pero dejan de mandar. ✨", True),
    ("«Tengo que ponerme las pilas.»\n\n*¿Quién dio esa orden,\nexactamente?*",
     "Es una propuesta disfrazada de orden. Y con las propuestas se negocia. 🤍", True),
    ("Estoy teniendo\nel pensamiento de que\n*no valgo para esto.*",
     "Pruébalo. Esa frase larga te devuelve a la escena. 🌿", True),
    ("Cansada a las siete de la tarde,\ntodo parece peor.\n*No es tu vida.\nEs la hora.*",
     "Estoy mirando desde el cansancio. Esto lo reviso mañana. 🌙", True),
    # 61
    ("Reconocer que duele.\nRecordar que no eres la única.\n*Hablarte como a alguien\nque quieres.*",
     "Tres movimientos. En ese orden. 🤍", True),
    ("Tratarte bien\nno te vuelve conformista.\n*Te deja mirar tus errores\nsin que te destruyan.*",
     "La dureza no produce responsabilidad. Produce evasión. ✨", True),
    ("Dejar de ser\n*la persona que peor te habla*\nen toda tu vida.",
     "Eso es todo. Ni frases en el espejo ni golpecitos en la espalda. 🤍", True),
    ("El miedo es un buen\nmotor de arranque\n*y un pésimo\nmotor de crucero.*",
     "Sirve para emergencias. No para sostener una vida entera. 🌿", True),
    ("Si el método duro\nfuera eficaz,\n*¿no lo habrías notado ya?*",
     "Llevas años usándolo. Tienes datos de sobra. 🤍", True),
    ("Una emoción\nse parece más al clima\n*que a un intruso.*",
     "Llega, ocupa un rato y se va sola si no la alimentas. 🌧️", True),
    ("Aceptar lo que sientes\n*no es aprobar\nlo que pasó.*",
     "Puedes aceptar que estás furiosa y seguir cambiando lo que te pone furiosa. ✨", True),
    ("La última vez que lloraste\nde verdad,\n*a la hora estabas\nhaciendo la cena.*",
     "Sentir no es hundirse. Nunca te hundiste. 🤍", True),
    ("La energía que gastabas\nhuyendo\n*era la que te faltaba\npara vivir.*",
     "Diez minutos con lo que sientes valen más que una semana evitándolo. 🌿", True),
    ("No hace falta\nque todo dolor\n*te haya enseñado algo.*",
     "Hay cosas que simplemente estuvieron mal. Puedes soltarlas igual. 🤍", False),
    # 71
    ("El rencor quiere algo.\n*El juicio solo constata.*",
     "Si ya no quieres nada de esa persona, ya soltaste. Aunque no hayas perdonado. 🌿", True),
    ("Puedes soltar\n*sin perdonar.*",
     "El perdón no es un deber. Es, como mucho, un final posible. 🤍", True),
    ("Cuando lo recuerdas,\n¿duele un momento\n*o se te va la tarde?*",
     "No mires el recuerdo. Mira lo que viene detrás. ✨", True),
    ("«Tengo tanto\nque agradecer.»\n\n*¿Y qué estabas sintiendo\njusto antes?*",
     "Si la gratitud llega para taparte, no es gratitud. 🌿", True),
    ("No mi familia.\n*La cara que puso mi hija\ncuando entendió el chiste.*",
     "La gratitud que funciona es concreta. Y dura dos segundos. 💛", True),
    ("La gratitud de verdad\nno sustituye lo que sientes.\n*Se suma.*",
     "Puedes estar agradecida y agotada a la vez. 🤍", True),
    ("Una meta se cumple.\n*Un valor se vive.*",
     "Y una dirección te da algo hoy, no dentro de ocho meses. 🌿", True),
    ("¿Me acerqué o me alejé\nde lo que me importa?\n*Esa pregunta\nsí tiene respuesta hoy.*",
     "«¿Llegué o no llegué?» casi nunca la tiene. ✨", True),
    ("A quien envidias\nte señala\n*algo que quieres\ny no te estás dando.*",
     "La envidia es un detector precisísimo. Úsalo. 🌿", True),
    ("No aspires\na no fallarte nunca.\n*Aspira a darte cuenta\ncada vez antes.*",
     "Tres días después. Esa noche. Diez minutos después. Justo antes de contestar. 🤍", True),
    # 81
    ("El miedo\nse disfraza de prudencia\n*con una facilidad\nextraordinaria.*",
     "¿Cuál de las dos opciones elegirías si no tuvieras miedo? 🌿", True),
    ("El alivio\nafloja los hombros.\n*La resignación\nlos sube.*",
     "Tu cuerpo ya sabe qué decidiste. 🤍", True),
    ("No fallaste tú.\n*Caducó el mapa.*",
     "Lo que necesitas es una brújula, no un plan definitivo. 🧭", True),
    ("Estás fregando los platos\n*y no estás fregando\nlos platos.*",
     "Tu vida entera ocurre aquí. No hay otro sitio donde pueda ocurrir. 🤍", True),
    ("Pagas dos veces\n*por algo que quizá\nno ocurra nunca.*",
     "Ensayar una discusión que no ha pasado también cansa. 🌿", True),
    ("Si no va a producir\nninguna acción,\n*no estás pensando.\nEstás rumiando.*",
     "Y la rumia no cuida de nada. Solo se come el día. ✨", True),
    ("Distraerte\n*no es el error.*\nVolver es el ejercicio.",
     "La que se distrae cien veces tiene cien oportunidades de volver. 🤍", True),
    ("Mismo tema.\n*Otra altura.*",
     "Desde dentro parece el mismo sitio. Desde un lado se ve que subía. 🌿", True),
    ("No preguntes\n«¿por qué sigo igual?».\nPregunta\n*«¿qué es distinto esta vez?».*",
     "Casi siempre hay algo. Y lo construiste tú. 💛", True),
    ("Un domingo a las siete\n*no es buen momento\npara evaluar tu vida.*",
     "Y sin embargo es justo cuando lo hacemos. 🌙", True),
    # 91
    ("Hay personas\ncon las que te vuelves *más.*\nY otras con las que\nte vuelves *menos.*",
     "Fíjate en cómo sales de estar con alguien. ✨", True),
    ("Donde no se puede\ncambiar de opinión,\n*no se puede pensar.*",
     "Solo se puede defender. 🌿", True),
    ("Las que te quieren de verdad\n*se alegran antes\nde preguntar el precio.*",
     "Etiqueta a la que siempre se alegra primero. 💛", True),
    ("«Ojalá te dure.»",
     "Hay frases que no son un ataque. Son un aire que se enfría. 🤍", False),
    ("Cuando justificas\nun límite,\n*abres una negociación.*",
     "Cada razón que das es un punto que la otra persona puede discutir. 🌿", True),
    ("Puedes ser cariñosísima\n*y no dar\nni una sola razón.*",
     "Ser amable no es dar explicaciones. ✨", True),
    ("No fuiste brusca.\n*Solo estás\ndesacostumbrada.*",
     "Para la primera vez que digas que no sin explicarte. 🤍", True),
    ("Rutinas que sostienen\ny rutinas que castigan.\n*Desde fuera\nse parecen mucho.*",
     "Si la dejaras mañana, ¿sentirías alivio? Entonces nunca fue tuya. 🌿", True),
    ("Copiar su horario\nno te da su vida.\n*Te da su horario\nen una vida que no lo admite.*",
     "Tu sistema ya existe. Solo hay que mirarlo. ✨", True),
    ("Elige una sola cosa.\nHazla tan pequeña\n*que te dé risa.*\nY sostenla un mes.",
     "Lo mínimo está fuera del juego de la deuda. Por eso dura. 💛", True),
    # 101
    ("El tamaño del propósito\nes proporcional\n*a la deuda que sientes.*",
     "Por eso los propósitos enormes se rompen a las dos semanas. 🌿", True),
    ("El silencio\ndespués de decir algo\n*es la parte más difícil.\nY la más útil.*",
     "Di lo que hay. Y luego cállate. 🤍", True),
    ("Que alguien se moleste\n*no significa\nque te equivocaste.*",
     "Los límites decepcionan a alguien. Por definición. ✨", True),
    ("Un día vas a decir que no,\ncolgar el teléfono\n*y ponerte a hacer la cena\nsin pensar más en ello.*",
     "Ese día no habrás cambiado de personalidad. Solo habrás dejado de creer que debías algo. 🤍", True),
    ("No hay una versión de ti\nque sea la buena.\n*Ya estás entera.*",
     "Vas a seguir creciendo. Pero no para completarte. 🌿", True),
    ("Nada de eso\nte va a completar,\n*porque no estabas\nincompleta.*",
     "Solo te va a hacer más ancha. ✨", True),
    ("Dos maneras de repasar el día:\n«¿qué me faltó?»\no\n*«¿desde dónde lo hice?»*",
     "La primera nunca queda satisfecha. La segunda sí. 🌙", True),
    ("Esa voz\n*nunca te felicita.*\nNi una sola noche.",
     "Fíjate esta noche. Es lo primero que hay que ver. 🌙", False),
    ("Lo hacía todo bien.\n*Ese era justamente\nel problema:*\ntodo bien,\npor el motivo equivocado.",
     "Yo fui la segunda mujer durante bastantes años. 🤍", False),
    ("La versión mejorada\nno era la condición\npara vivir así.\n*Era la excusa\npara no hacerlo todavía.*",
     "¿Qué harías si mañana ya fueras ella? Hazlo el jueves. 🌿", True),
    # 111
    ("Una dirección te dice\nhacia dónde.\n*Ella te dice\nque todavía no.*",
     "Esa mujer que llevas dentro: ¿te señala un camino, o te señala a ti? ✨", True),
    ("Dejar de pelear\nen una guerra\n*que ni siquiera sabías\nque estabas librando.*",
     "La rabia se pasa. Lo que queda es un descanso raro. 🤍", True),
    ("Nada de eso\nse resolvió solo.\n*Lo hiciste tú.*",
     "Piensa en dónde estabas hace cinco años. Ahora cuéntalo. 💛", True),
    ("Quiero llegar ahí\nno es lo mismo que\n*no valgo hasta llegar ahí.*",
     "Puedes tener metas altas. Solo revisa el punto de partida. 🌿", True),
    ("Crecer parte de\n*«estoy bien,\ny tengo curiosidad».*",
     "Repararte parte de «estoy rota, y voy con retraso». Mismas acciones. Otra vida. ✨", True),
    ("Para reparar algo,\nprimero tienes\nque *declararlo roto.*",
     "Cada vez que te propones repararte, firmas ese diagnóstico. 🤍", False),
    ("Nadie te está pidiendo\nque dejes de crecer.\n*Solo que mires\ndesde dónde.*",
     "Sigue leyendo. Sigue en terapia si te hace bien. Sigue cuidándote. 🌿", True),
    ("Hoy, ¿hubo algo bueno\n*que no llegaste a mirar?*",
     "Dos segundos. Ese es todo el ejercicio. ✨", True),
    ("No sumas:\n*pagas.*",
     "Cuando lo haces desde el miedo, cada paso solo sirve para no perder. 🌿", False),
    ("Sigue creciendo.\n*Solo que ya no\ndesde ahí.*",
     "Cierra el día y vete a hacer tus cosas. 🤍", True),
]
